### ISSUE TITLE
Going directly to subpage in demo results in a 404

### ISSUE THREAD

**Issue by NathanC** [christopher-caldwell/react-kanban#12]
If you navigate directly to a sub-path of the demo, such as [/react-kanban/uncontrolled](https://christopher-caldwell.github.io/react-kanban/uncontrolled), it results in a 404. This is because GitHub pages don't really support SPAs. It tries to serve up the actual path, instead of serving `index.html` for every path. 

It seems like there [is a way around this](https://stackoverflow.com/a/63492458/954986) but it's really hackish.

I'd recommend, instead, removing the sub-pages entirely, and using fragment based navigation. That would be kind of nice since the current home page is pretty barren anyways ("Welcome home") and when I first viewed the demo I didn't notice the upper right nav links.

Alternatively, since you're using a small number of known paths, you can just serve up [redirect pages](https://dev.to/steveblue/setup-a-redirect-on-github-pages-1ok7) for each of those paths. You'd probably want to do that anyhow for the `/` path, since it currently 404s instead of redirecting to `/react-kanban`

I can take a stab at fixing this one at some point.

**Comment by christopher-caldwell** [comment]
Yeah GH pages is pretty bad with React router. I did know this was happening, but didn't care that much lol. 

Since you're actually using it, I'll definitely fix it.

**Comment by christopher-caldwell** [comment]
Fixed and deployed. Can now access any demo with: https://christopher-caldwell.github.io/react-kanban
