### ISSUE TITLE
Add repository to hacktoberfest

### ISSUE THREAD

**Issue by Sabrinovsky** [christopher-caldwell/react-kanban#46]
https://hacktoberfest.com/participation/#pr-mr-details
@christopher-caldwell could you do it?

**Comment by christopher-caldwell** [comment]
@Sabrinovsky Could you give a quick overview of what this is/what to do? I have never heard of this.

**Comment by Sabrinovsky** [comment]
@christopher-caldwell it is a global event to incentive open source contribuition.
You can see more details here: https://hacktoberfest.com/
The challange is basically to create 4 PR for open source projects, but we have to add the topic to the repo participate.
You just have to add the hacktoberfest tag here: 
![image](https://github.com/user-attachments/assets/7f4d1c7f-8905-44f2-9697-7b8ea593a497)

**Comment by christopher-caldwell** [comment]
Ahh ok, cool. I added the tag.
