### ISSUE TITLE
css doesn't seem to be bundled in the dist

### ISSUE THREAD

**Issue by NathanC** [christopher-caldwell/react-kanban#7]
Hi! First off, thanks for creating this library. I always love seeing a library with excellent TypeScript support, and I'm looking forward to using this.

Anyhow, I'm setting it up, and it doesn't seem like the `.css` file you reference in the README is anywhere to be found in the dist. Maybe there's a bundler issue with the .scss you're using? Or maybe it's not not required anywhere and doesn't get bundled.

I'll just use the .scss from the repo directly for now :)

btw, another 2 other minor issue I noticed but don't seem worth filing their own issue for: 
1) when I type in a comenent (e.g., Card), VS Code doesn't autocomplete the import for me, it thinks its exported somewhere within the `dist` instead of from the top level module. I've noticed this rarely with some other libraries, so it's probably due to the way the types are exported
2) I can't just directly use `KanbanBoard`, I need to specify `KanbanBoard<Card>` explicitly in state/variable definitions.

Neither are a big deal, just an fyi. Let me know if you'd like me to file separate issues for them.

**Comment by christopher-caldwell** [comment]
@NathanC  Thanks for checking it out!

[This line](https://github.com/christopher-caldwell/react-kanban/blob/1b6f02baa8daa99bafc524af09404b5d5fb92ed8/scripts/build.sh#L7) is supposed to add that file to the `dist`. I will take a look and see what's up.

Re the `Card`, you should definitely be able to import them directly without accessing `dist`. How are you consuming this? Next, CRA, Vite, etc?

**Comment by NathanC** [comment]
@christopher-caldwell Unfortunately I've never used yarn, so can't help out here.

> How are you consuming this?

CRA. I can import it correctly and it works fine, I'm just referring to a minor issue which is that VS Code doesn't seem to autocomplete the import. Meaning if I start typing `<Card` and haven't imported it yet, vs code gives me the option to import from the dist (and then doesn't even add the import when I select that option), as opposed to importing from the top level module for the library.

No idea why, and it's minor, just wanted to mention it :)

**Comment by christopher-caldwell** [comment]
In npm, this translates to `npx sass`. It's just asking yarn to find the binary for the library and use it. That's not a major concern. 

Tomorrow, I'll make a fresh CRA and see if I can reproduce it and troubleshoot. 

Ahh, I see about Card. Thanks for bringing it up, I can put a blurb in the README about it.
