### ISSUE TITLE
Dragging does not work with React.StrictMode in React 18

### ISSUE THREAD

**Issue by NathanC** [christopher-caldwell/react-kanban#8]
Kind of a strange issue. I'm using controlled components, and testing out this library-- and dragging/dropping did not work at all.  It gave the error `Unable to find draggable with id:  1`, which was an error from the dnd library (and said the error will not show in production).

I dug into this a bit, and apparently this is a known issue in the `dnd` library, which, as I understand it, is no longer maintained. See the issue thread here: https://github.com/atlassian/react-beautiful-dnd/issues/2350

One comment claims they fixed it with a fork that properly supports React 18, see here: https://github.com/atlassian/react-beautiful-dnd/issues/2350#issuecomment-1213991252 The fork seems quite popular, ~300 stars, and has recent development.

Since you're forking an unmaintained library with an unmaintained dependency, might be a good idea to switch to this `dnd` fork-- forks all the way down!

If not, adding something to the README about removing strict mode is a good quick "fix", and some other potential workarounds you can do w/o changing your dependency may be referenced in the issue thread above.

**Comment by christopher-caldwell** [comment]
Agreed! I will checkout swapping the forked one. Thanks!

**Comment by NathanC** [comment]
@christopher-caldwell Thanks for the quick fix! It's nice having this depend on a non-archived library now, should stay more up to date.

I tested this downstream in React 18 with strict mode (using v0.0.5), and it works like a charm :)

**Comment by christopher-caldwell** [comment]
@NathanC Sure thing! 

It helps a lot to get issues, as I only tested this with 17. Keep em coming!

**Comment by NathanC** [comment]
@christopher-caldwell  I just noticed a regression. After updating, when I hover over draggable items, the cursor *initially* isn't `grab`.

I can still grab though, and once I grab any item, all other items have the grab cursor in the future.

Looking specifically at the column header grab div (css: `[data-rfd-drag-handle-context-id="1"]`), it doesn't have `cusor: grab` initially when I load the page, then when *anything* is dragged it changes to "pointer-events: none", then after that it does add `cursor: grab`.

I don't see this in the demo though. Any idea what might cause this? Seems like potentially an upstream bug, but I'm curious if you see it at all in your stuff. I just fixed it for myself with a manual `cursor: grab` rule on the column header and my custom card.

**Comment by christopher-caldwell** [comment]
So this wasn't an issue with the previous versions, namely using react-beautiful-dnd? I'll try to reproduce with the older versions. If the issue is there in the previous, then that makes sense. Otherwise hmm. Probably an easy fix in the source, just need to see why.

**Comment by NathanC** [comment]
It's possible I just didn't notice it before. It's easy to fix with some css, so not a critical issue-- you can just apply default css to all draggable components. I'm more concerned that this is a symptom of an actual issue that would impact accessibility or something, but I don't know nearly enough to see if that's the case.
